declare const styles: {
    readonly wrapper: string;
    readonly graySection: string;
    readonly column: string;
    readonly listColumn: string;
    readonly title: string;
    readonly price: string;
    readonly priceMonth: string;
    readonly activationPrice: string;
    readonly descriptionPrice: string;
    readonly list: string;
    readonly listItem: string;
    readonly listIcon: string;
    readonly link: string;
    readonly toolTip: string;
    readonly buttonWrapper: string;
    readonly button: string;
    readonly buttonDesktop: string;
    readonly buttonMobile: string;
};
export = styles;
